### ISSUE TITLE
Error when analyzing a particle with two skeletons

### ISSUE THREAD

**Issue by hansenjn** [hansenjn/CiliaQ#1]
In timelapse mode, when a particle is analyzed that produces two skeletons in a few frames, the program crashes.
**CiliaQ version:** v0.0.7
**Error message:**
`java.lang.NullPointerException
	at ciliaQ_jnh.CiliaQMain.analyzeCiliaIn4DAndSaveResults(CiliaQMain.java:2481)
	at ciliaQ_jnh.CiliaQMain.run(CiliaQMain.java:436)
	at net.imagej.legacy.IJ1Helper.run(IJ1Helper.java:753)
	at net.imagej.legacy.LegacyCodeRunner.run(LegacyCodeRunner.java:61)
	at org.scijava.run.RunService.run(RunService.java:59)
	at org.scijava.plugins.scripting.java.JavaEngine.eval(JavaEngine.java:137)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by hansenjn** [comment]
Solved with CiliaQ version v.0.0.8
