### ISSUE TITLE
Null Pointer Exception during running

### ISSUE THREAD

**Issue by hansenjn** [hansenjn/CiliaQ#2]
When analyzing a 3D image of cilia, the following error occured for an unknown reason:
`java.lang.NullPointerException
	at ciliaQ_jnh.CiliaQMain.analyzeCiliaIn3DAndSaveResults(CiliaQMain.java:2049)
	at ciliaQ_jnh.CiliaQMain.run(CiliaQMain.java:440)
	at ij.IJ.runUserPlugIn(IJ.java:221)
	at ij.IJ.runPlugIn(IJ.java:185)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by hansenjn** [comment]
Issue solved in version [v0.0.9](https://github.com/hansenjn/CiliaQ/releases/tag/v0.0.9).
